default_stages: [commit, push]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    - id: check-json
    - id: check-toml
    - id: check-merge-conflict
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: pretty-format-json
      args: ["--autofix", "--no-sort-keys"]
  - repo: https://github.com/ambv/black
    rev: 21.12b0
    hooks:
    - id: black
      args: ["-l 120"]
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: ["--profile", "black"]
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.31.0
    hooks:
    - id: pyupgrade
      args: ["--py38-plus"]
  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
    - id: flake8
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: 'v0.910-1'  # Use the sha / tag you want to point at
  #   hooks:
  #   - id: mypy
